### ISSUE TITLE
Charts did not perfectly fit  in flexdashboard

### ISSUE THREAD

**Issue by ThoDuyNguyen** [mrjoh3/pier#1]
You could go here for my Rmarkdown: 

https://gist.github.com/ThoDuyNguyen/c1a4f42fd160faaa67a3eb25af2ba58e#file-gistfile1-txt

**Comment by mrjoh3** [comment]
Hi Tho

Unfortunately sizing is not currently dynamic in this package. It is
clearly the preferred method so I will try and fix this as soon as possible

**Comment by ThoDuyNguyen** [comment]
Thank you for the quick reply

**Comment by mrjoh3** [comment]
@ThoDuyNguyen filling dashboard frame and resizing should now work. See [gist](https://gist.github.com/mrjoh3/5e5383d6c5078c3ceb96e45c1fd359d7)

**Comment by mrjoh3** [comment]
this last commit should fix all resizing issues with `flexdashboard`. I have tested the new .resize() function in the rstudio viewer, regular rmd files and flexdashboard tabs. It all works as expected. If you are able please double check flexdashboard as there are a lot of different ways to display widgets in the dashboard and they should work as expected but I have not tested all use cases.

**Comment by ThoDuyNguyen** [comment]
The new dev version fixed the issue. 
Case is closed.
