### ISSUE TITLE
resizing results in multiple piecharts

### ISSUE THREAD

**Issue by zhiboz** [mrjoh3/pier#2]
the pie chart shows up fine with the following code

``` R
library(shiny)
library(pier)

shinyApp(
  ui = dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
      fluidRow(
        box(
          title = "Distribution",
          status = "primary",
          pierOutput("pie", height = 240),
          height = 300
        )
      )
    ),
    title = "Dashboard example"
  ),
  server = function(input, output) { 
    output$pie <- renderpier({
      data.frame(value = c(40, 20, 30),
                 label = c('red', 'green', 'blue'),
                 color = c('red', 'green', 'blue')) %>%
        pier()
    })
  }
)
```

but when you resize the window, multiple pie charts (identical chart in different sizes) show up.

<img width="955" alt="screen shot 2016-10-19 at 9 18 44 am" src="https://cloud.githubusercontent.com/assets/2729326/19520125/188abb8c-95dd-11e6-9fa7-605293990029.png">

**Comment by hiffman** [comment]
Hello, I also encountered this problem, I think should be a compatibility issue in shiny. And I find a More serious problem that the percentages add up to equal 101% or 99%.,your picture also show this problem.
Maybe the rounding lead to this problem.

**Comment by zhiboz** [comment]
I guess this issue

>  the percentages add up to equal 101% or 99%.

is related to d3pie.js itself instead of this htmlwidget, as you would observe the same thing from some of its demos, for instance

http://d3pie.org/website/examples/donut.html

**Comment by mrjoh3** [comment]
Hi All

I am hoping to have a look at this over the weekend

**Comment by zhiboz** [comment]
that'd be appreciated! I think the issue is caused by the `resize` function at `line 69` in `inst/htmlwidgets/pier.js`

`draw_pie(x);`

which creates a new pie chart on each resize

```
    var draw_pie = function(x) {

            pie = new d3pie(x.id, {
                header: x.header,
                size: x.size,
                footer: x.footer,
                tooltips: x.tooltips,
                labels: x.labels,
                effects: x.effects,
                misc: x.misc,
                data: x.data
            });

    }
```

**Comment by mrjoh3** [comment]
Hi @zhiboz the last commit should fix the issue. You were right about the location of the issue, but the `draw_pie(x)` function is needed for the plots to be responsive. I'm not sure why resize gets called multiple times by shiny, this might cause a slight shudder while resizing but the final plot should be ok.

**Comment by ngfrey** [comment]
@mrjoh3, take a look at my pull request for #4. I think it may also resolve this issue.

**Comment by mrjoh3** [comment]
thanks @ngfrey PR accepted
