### ISSUE TITLE
Pier only plots after resize in Shiny

### ISSUE THREAD

**Issue by mhairi** [mrjoh3/pier#3]
I've found a couple of problems working with pier and shiny. I'm going to split them across two issues. First of all, it seems the pier plot only appears after you resize the browser in Shiny. 

For example:

``` r
library(shiny)
library(pier)

ui <- fluidPage(
         pierOutput("pier_example")
)

server <- function(input, output) {
   
   output$pier_example <- renderpier({
      data.frame(
        value = c(30, 70),
        label = c('Red', 'Blue'),
        color = c('Red', 'Blue')
      ) %>%
      pier()
   })
}

shinyApp(ui = ui, server = server)
```

In the above app the pie chart only appears for me after I resize the browser. I think this could be related to this issue: https://github.com/mrjoh3/pier/issues/2

**Comment by mrjoh3** [comment]
thanks for the code I was able to reproduce the problem. I have implemented a temporary fix that will identify when the plot is being rendered in shiny. For now just add `pier() %>% pie.size()` to your example above. `pie.size()` is needed.

I will have to change my resize implementation. Rmd files, flexdashboards and shiny all render differently . In this case the widget thought it was being inserted into a div of zero height and so it was not visible. Hopefully I will get it sorted over the next week

**Comment by mrjoh3** [comment]
hi @mhairi I think is is now working as well as it can. pier() will now work by itself and default to a 500 px radius. I am still not able to get the chart to detect the size of the container as the height comes through as 0 or 'undefined'. If you have a look at the console log in the browser you can see some of the values.

please let me know how it is behaving at your end

**Comment by mhairi** [comment]
Looks good on my end. Thank you very much for sorting this out!
