### ISSUE TITLE
Changing input results in multiple plots 

### ISSUE THREAD

**Issue by mhairi** [mrjoh3/pier#4]
Again I think this issue is related to https://github.com/mrjoh3/pier/issues/2 and my other issue https://github.com/mrjoh3/pier/issues/3

In the below app:

```r
library(shiny)
library(pier)

ui <- fluidPage(
          sliderInput("percent",
                      "Size of slice",
                      0, 100, 30),
         pierOutput("pier_example")
)

server <- function(input, output) {
   
   output$pier_example <- renderpier({
      data.frame(
        value = c(input$percent, 100 - input$percent),
        label = c('Red', 'Blue'),
        color = c('Red', 'Blue')
      ) %>%
      pier()
   })
}

shinyApp(ui = ui, server = server)
```

Every time I change the input the plot redraws below the existing plot, rather than replacing the existing plot.

**Comment by ngfrey** [comment]
I can confirm I have this issue as well. I have tried isolating it in iframes, but that brings about more issues with htmlwidgets and chasing down weird settings in the DOM than solutions.

**Comment by ngfrey** [comment]
@mhairi I took a look at this and **think** I was able to fix it with a couple of lines of code. I added a check to see if a past pie chart was created inside the `render` function and, if so, destroy the past pie chart prior to rendering a new pie. I tested this in a shiny dashboard and I haven't seen any extra pie charts show up when switching inputs. I'm going to submit a pull request.
